zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    job:
      timeout: 10000
      poll-interval: 100

server:
  port: 8090

logging:
  level:
    io.camunda: DEBUG
    com.example: DEBUG
    root: INFO